
import React, { useState } from 'react';
import Header from './components/Header';
import StockForm from './components/StockForm';
import AnalysisResult from './components/AnalysisResult';
import { StockInputs, AnalysisResult as AnalysisResultType, AnalysisStatus } from './types';
import { analyzeStock } from './services/geminiService';

const App: React.FC = () => {
  const [status, setStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [result, setResult] = useState<AnalysisResultType | null>(null);
  const [currentStock, setCurrentStock] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async (inputs: StockInputs) => {
    setStatus(AnalysisStatus.LOADING);
    setError(null);
    setCurrentStock(inputs.name);

    try {
      const data = await analyzeStock(inputs);
      setResult(data);
      setStatus(AnalysisStatus.SUCCESS);
    } catch (err) {
      console.error(err);
      setError('Failed to analyze stock. Please check your data or try again later.');
      setStatus(AnalysisStatus.ERROR);
    }
  };

  return (
    <div className="min-h-screen pb-20">
      <Header />
      
      <main className="max-w-6xl mx-auto px-4">
        <div className="mb-8 text-center md:text-left">
          <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">Financial Intelligence Dashboard</h2>
          <p className="text-slate-500 mt-2">Professional algorithmic analysis for smarter investment research.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          <div className="lg:col-span-4 sticky top-4">
            <StockForm onAnalyze={handleAnalyze} isLoading={status === AnalysisStatus.LOADING} />
            
            <div className="mt-8 p-6 bg-amber-50 rounded-2xl border border-amber-200 flex gap-4">
              <div className="text-amber-600 pt-1">
                <i className="fa-solid fa-circle-info text-xl"></i>
              </div>
              <div className="text-sm text-amber-900 leading-relaxed">
                <p className="font-bold mb-1 uppercase tracking-tight text-[10px]">Important Disclaimer</p>
                This analysis is generated by AI for educational and information purposes only. It is NOT financial advice. Always consult a certified financial advisor before making any investment decisions.
              </div>
            </div>
          </div>

          <div className="lg:col-span-8">
            {status === AnalysisStatus.IDLE && (
              <div className="bg-slate-100 border-2 border-dashed border-slate-300 rounded-2xl h-[600px] flex flex-col items-center justify-center text-slate-400 p-12 text-center">
                <i className="fa-solid fa-chart-area text-6xl mb-6 opacity-20"></i>
                <h3 className="text-xl font-bold text-slate-500">Awaiting Data Input</h3>
                <p className="max-w-xs mt-2">Fill out the stock fundamental details on the left to generate a comprehensive AI-powered analyst report.</p>
              </div>
            )}

            {status === AnalysisStatus.LOADING && (
              <div className="bg-white border border-slate-200 rounded-2xl h-[600px] flex flex-col items-center justify-center p-12 text-center animate-pulse">
                <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mb-6">
                  <i className="fa-solid fa-brain text-3xl text-indigo-500 animate-bounce"></i>
                </div>
                <h3 className="text-xl font-bold text-slate-900">Gemini is Reasoning...</h3>
                <p className="text-slate-500 mt-2 max-w-sm">
                  Our financial neural network is cross-referencing fundamentals, assessing valuation multiples, and projecting risk scenarios for {currentStock}.
                </p>
              </div>
            )}

            {status === AnalysisStatus.ERROR && (
              <div className="bg-rose-50 border border-rose-200 rounded-2xl p-12 text-center">
                <div className="w-16 h-16 bg-rose-100 rounded-full flex items-center justify-center mx-auto mb-6">
                  <i className="fa-solid fa-circle-exclamation text-3xl text-rose-500"></i>
                </div>
                <h3 className="text-xl font-bold text-rose-900">Analysis Interrupted</h3>
                <p className="text-rose-700 mt-2">{error}</p>
                <button 
                  onClick={() => setStatus(AnalysisStatus.IDLE)}
                  className="mt-6 bg-rose-600 text-white px-6 py-2 rounded-lg font-bold hover:bg-rose-700 transition-all"
                >
                  Reset Dashboard
                </button>
              </div>
            )}

            {status === AnalysisStatus.SUCCESS && result && (
              <AnalysisResult data={result} stockName={currentStock} />
            )}
          </div>
        </div>
      </main>

      <footer className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200 py-3 px-6 text-center text-slate-400 text-xs">
        <p>&copy; 2024 AI Stock Analyst System. Powered by Google Gemini 3 Flash. Built for education.</p>
      </footer>
    </div>
  );
};

export default App;
